name: Download

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: download
        run: |
          wget https://cdn.openttd.org/opensfx-releases/1.0.3/opensfx-1.0.3-all.zip
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            https://cdn.openttd.org/opensfx-releases/1.0.3/opensfx-1.0.3-all.zip
