name: Download

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: download
        run: |
          wget https://www.kristendoherty.com.au/_files/ugd/02c41d_f556134c7fe3408c9794ec5a0d923226.pdf
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            02c41d_f556134c7fe3408c9794ec5a0d923226.pdf
